[package]
name = "lines-of-code"
description = "measure lines of code"
authors = ["Ben <kaleidawave@gmail.com>"]
version = "0.0.0"
license = "MIT"
edition = "2024"
repository = "https://github.com/kaleidawave/experiments"
publish = false

[lib]
path = "lib.rs"

[[bin]]
name = "lines-of-code"
path = "main.rs"

[package.metadata.commands]
test = "spectra check README.md 'target/debug/lines-of-code --rpc --interactive'"

[dependencies]
glob = "0.3.3"
json-builder-macro = "=0.0.3"

derive_more.version = "2.1.1"
derive_more.default-features = false
derive_more.features = ["add", "add_assign"]
