[package]
name = "rust-type-sizes"
description = "parsing for '-Zprint-type-sizes'"
version = "0.0.0"
edition = "2024"
authors = ["Ben <kaleidawave@gmail.com>"]
license = "MIT"
keywords = ["rust", "type sizes"]
repository = "https://github.com/kaleidawave/experiments"

[dependencies]

[lib]
path = "lib.rs"

[[bin]]
name = "rust-type-sizes"
path = "main.rs"
