[package]
name = "script-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
simple-toml-parser = { git = "https://github.com/kaleidawave/simple-toml-parser.git", branch = "improvements" }

[[bin]]
name = "script-runner"
path = "./main.rs"

[package.metadata.commands]
echo = "./target/debug/examples/echo.exe hello world"
