[package]
name = "general-parser"
version = "0.0.4"
authors = ["Ben <kaleidawave@gmail.com>"]
edition = "2024"
description = "Configurable parser for S-expressions with configurable extensions for mathematical notation"
license = "MIT"
categories = ["text-processing", "compilers", "parsing"]
keywords = ["parsing", "operators"]
repository = "https://github.com/kaleidawave/experiments"

[features]
default = ["stable"]
stable = ["dep:allocator-api2", "bumpalo/allocator-api2"]

[dependencies]
allocator-api2 = { version = "=0.2.21", optional = true }
bumpalo = { version = "3.19.0", features = ["collections"] }

[[test]]
name = "specification"
harness = false

[package.metadata]
associated = ["javascript/jsr.json", "javascript/package.json"]

[package.metadata.commands]
spectra = 'spectra check ./specification.md "./target/debug/examples/parse --rpc --interactive"'
