[package]
name = "date-utilities"
version = "0.0.3"
edition = "2024"
description = "Lightweight utilities for working with dates. Expect minimal functionality"
license = "MIT"
categories = ["date-and-time"]
keywords = ["date", "now"]
repository = "https://github.com/kaleidawave/experiments"

[dependencies]
