[package]
name = "mashrl"
version = "0.0.3"
authors = ["Ben <kaleidawave@gmail.com>"]
edition = "2024"
description = "Minimal and simple HTTP(s) request library"
license = "MIT"
categories = ["network-programming"]
keywords = ["http", "request"]
repository = "https://github.com/kaleidawave/experiments"

[lib]
path = "lib.rs"

[features]
decompress = ["dep:flate2"]

[dependencies]
flate2 = { version = "1.1.2", optional = true }
native-tls = "0.2.14"
