name: Check experiment

on:
  push

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          dynamic-library: libqbdi_tracer.so
        - os: macos-latest
          dynamic-library: libqbdi_tracer.dylib
        - os: windows-latest
          dynamic-library: libqbdi_tracer.dll
          executable-extension: '.exe'

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: jwlawson/actions-setup-cmake@v2
      with: { cmake-version: '3.31.7' }
    
    - name: Check
      run: cargo check
      working-directory: benchmarking-tool

    - name: Get QBDI (linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run:
        curl https://github.com/QBDI/QBDI/releases/download/v0.12.0/QBDI-0.12.0-ubuntu24.04-X86_64.deb -L > QBDI.deb
        sudo dpkg -i QBDI.deb
    
    - name: Get QBDI (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        curl https://github.com/QBDI/QBDI/releases/download/v0.12.0/QBDI-0.12.0-osx-AARCH64.pkg -L > QBDI.pkg
        sudo installer -pkg QBDI.pkg -target ~
    
    - name: Get QBDI (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        curl https://github.com/QBDI/QBDI/releases/download/v0.12.0/QBDI-0.12.0-windows-X86_64.exe -L > QBDI.exe
        ./QBDI.exe
        
    - name: Build binary, example and QBDI
      working-directory: benchmarking-tool
      shell: bash
      run: |
        cargo build
        mv target/debug/benchmark .
        
        bash build-qbdi.sh
        mv 'qbdi/build/${{ matrix.dynamic-library }}' .

    - name: Build and run iterations
      working-directory: benchmarking-tool
      shell: bash
      run: |
        cargo build --example iterations
        mv target/debug/examples/iterations${{ matrix.executable-extension }} .

        for i in {0..3}
        do
          i=$((10**i))

          echo "::group::benchmark${{ matrix.executable-extension }} qbdi ./iterations${{ matrix.executable-extension }} $i"
          ./benchmark${{ matrix.executable-extension }} qbdi ./iterations${{ matrix.executable-extension }} $i
          echo "::endgroup::"
        done

    - name: Setup SDE binaries
      if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
      uses: petarpetrovt/setup-sde@v3.0
      with:
        environmentVariableName: SDE_PATH # default value is `SDE_PATH`
        sdeVersion: 9.58.0 # possible values: 9.58.0 (default), 9.33.0

    - name: Run SDE (linux or windows)
      if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
      run:
        for i in {0..3}
        do
          i=$((10**i))

          echo "::group::benchmark${{ matrix.executable-extension }} sde ./iterations${{ matrix.executable-extension }} $i"
          ./benchmark${{ matrix.executable-extension }} sde ./iterations${{ matrix.executable-extension }} $i
          echo "::endgroup::"
        done

  publish-assets:
    needs: check

    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: windows-latest
          platform-name: x86_64-pc-windows
          executable-extension: ".exe"
          dynamic-library: libqbdi_tracer.dll
        - os: ubuntu-latest
          platform-name: x86_64-unknown-linux
          dynamic-library: libqbdi_tracer.so
        - os: macos-latest
          platform-name: aarch64-apple-darwin
          dynamic-library: libqbdi_tracer.dylib

    runs-on: ${{ matrix.os }}

    env:
      PROFILE: dev
      OUT: target/debug
      GH_RELEASE: assets

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        working-directory: benchmarking-tool
        run: cargo build --profile ${{ env.PROFILE }}

      - name: Publish binary
        working-directory: benchmarking-tool
        shell: bash
        env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
        run: |
          bash build-qbdi.sh
          mv 'qbdi/build/${{ matrix.dynamic-library }}' .

          FROM='${{ env.OUT }}/benchmarking-tool${{ matrix.executable-extension }}'
          TO='benchmark-${{ matrix.platform-name }}${{ matrix.executable-extension }}'
          mv $FROM $TO
          gh release upload $GH_RELEASE "$TO" --clobber
          gh release upload $GH_RELEASE "${{ matrix.dynamic-library }}" --clobber

