name: Build assets for projects

on:
  push

jobs:
  publish-assets:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        binary: [
          path-fs-utilities~find-empty,
          path-fs-utilities~hosts-tool,
        ]
        include:
        - os: windows-latest
          platform-name: x86_64-pc-windows
          executable-extension: ".exe"
        - os: ubuntu-latest
          platform-name: x86_64-unknown-linux
        exclude:
        - os: ubuntu-latest
          binary: path-fs-utilities~hosts-tool

    runs-on: ${{ matrix.os }}

    env:
      PROFILE: dev
      OUT: target/debug
      GH_RELEASE: assets

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Set variables
        id: information
        shell: bash
        run: |
          echo "GITHUB_RUN_DATE=$(TZ="Europe/London" date +"%Y-%m-%d %T")" >> "$GITHUB_OUTPUT"
          echo "GIT_LAST_COMMIT=$(git log -n 1 --format="%H")" >> "$GITHUB_OUTPUT"

          IFS='~' read -r binary example <<< '${{ matrix.binary }}'
          echo "WORKING_DIRECTORY=$binary" >> "$GITHUB_OUTPUT"
          if [ -n "$example" ]; then
            echo "BUILD_SPECIFIER=--example $example" >> "$GITHUB_OUTPUT"
            echo "ASSET_PATH=${{ env.OUT }}/examples/$example" >> "$GITHUB_OUTPUT"
            echo "ASSET_NAME=$example" >> "$GITHUB_OUTPUT"
          else
            echo "BUILD_SPECIFIER=" >> "$GITHUB_OUTPUT"
            echo "ASSET_PATH=${{ env.OUT }}/$binary" >> "$GITHUB_OUTPUT"
            echo "ASSET_NAME=$binary" >> "$GITHUB_OUTPUT"
          fi

      - name: Build binary
        working-directory: ${{ steps.information.outputs.WORKING_DIRECTORY }}
        run: cargo build ${{ steps.information.outputs.BUILD_SPECIFIER }} --profile ${{ env.PROFILE }}
        env:
          GITHUB_RUN_DATE: ${{ steps.information.outputs.GITHUB_RUN_DATE }}
          GIT_LAST_COMMIT: ${{ steps.information.outputs.GIT_LAST_COMMIT }}

      - name: Publish binary
        working-directory: ${{ steps.information.outputs.WORKING_DIRECTORY }}
        shell: bash
        env: { "GH_TOKEN": "${{ secrets.GITHUB_TOKEN }}" }
        run: |
          FROM="${{ steps.information.outputs.ASSET_PATH }}${{ matrix.executable-extension }}"
          TO="${{ matrix.binary }}-${{ matrix.platform-name }}${{ matrix.executable-extension }}"
          gh release upload $GH_RELEASE "$FROM#$TO" --clobber