name: Check experiment

on:
  push

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ["str-utilities"]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Check
      run: cargo check
      working-directory: ${{ matrix.project }}

    - name: Test
      run: cargo test
      working-directory: ${{ matrix.project }}

    - name: Lint
      run: cargo clippy
      working-directory: ${{ matrix.project }}